### PR TITLE
Course Description, Perks

### LINKED ISSUE #92: Create Course Description
## Is your feature request related to a problem? Please describe.

On the course details page, 'course description' and 'after course' sections are still left to implement. Reference - #1 #2 

## Describe the solution you'd like

'Course description' component and 'after course' component can be made to complete the course details page.

Screenshot 2021-03-14 174918
Screenshot 2021-03-14 174944

### PR DESCRIPTION
**Pull request by faisaljamil25**
**Issue Number**

fixes #92 

**Describe the changes you've made**

Created course description section and course perks section.
Created `courseDetail.json` file to store all the data of course detail page so that more course can be added without changing the main code.
Refactor whole course detail page and added schedule section.

**Describe if there is any unusual behavior (Any Warning) of your code(Write `NA` if there isn't)**

NA

**Test plan (OPTIONAL)**

visit [http://localhost:3000/course/1](URL) to see the course detail page.

**Checklist**

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by faisaljamil25** [comment]
Screenshots

Screenshot 2021-03-15 204013

Screenshot 2021-03-15 204051

Screenshot 2021-03-15 204153

Screenshot 2021-03-15 204225

**Comment by faisaljamil25** [comment]
@Abhishek-kumar09 please review this and let me know any suggestions.

**Comment by Abhishek-kumar09** [comment]
I will be reviewing your changes positively by tomorrow. Thanks for the PR.

**Comment by KeenWarrior** [comment]
Hey @faisaljamil25 Sorry for the delay

Can you please fix the conflicts and let us know.

**Comment by faisaljamil25** [comment]
@KeenWarrior fixed all conflicts and transferred all course detail page data to `courseDetail.json` file so that more courses can be added without changing the main code. Let me know if anything needs to be changed.

**Comment by Abhishek-kumar09** [comment]
Looks good

**Pull request merged**
