### PR TITLE
UI: Added Hero Component and Course Detail Page

### LINKED ISSUE #3: Create Hero for Course Detail Page
Part 1 of #2

image

Compoenents are required to be made with material-ui: https://material-ui.com/

### PR DESCRIPTION
**Pull request by rizwan2000rm**
### Issue Number

fixes #3 

### Describe the changes you've made

Added responsive Hero component for the Course Detail page. Also added a new CourseDetail page on route /course/:id 

### Describe if there is any unusual behavior (Any Warning) of your code(Write `NA` if there isn't)

Getting problems with Scroll Behaviour after recent pull, anything after the viewport width is unreachable. It probably has to do with some other commit in Layout component as I have tested this on several pages and got the same issue but it was working fine prior to the pull changes.

### CODE REVIEW

**Comment by Abhishek-kumar09** [comment]
> Getting problems with Scroll Behaviour after recent pull, anything after the viewport width is unreachable. It probably has to do with some other commit in Layout component as I have tested this on several pages and got the same issue but it was working fine prior to the pull changes.

Fixed with https://github.com/codeforcauseorg/edu-client/commit/44c916fa4fe8eeeea6b2eaebe08aa036fc01e1c6 rebase your changes

**Comment by rizwan2000rm** [comment]
@Abhishek-kumar09 Okay, I will do it. Does the UI looks good ?

**Comment by rizwan2000rm** [comment]
@Abhishek-kumar09 rebasing is causing issues as I have already pushed changes to my fork. Instead of force pushng I have merged the changes. If we need a single commit then I would have to force push on my fork.

**Comment by Abhishek-kumar09** [comment]
First squash all your commits into one and then rebase, You will have no conflicts then

**Comment by KeenWarrior** [comment]
Please resolve conflicts.

**Comment by rizwan2000rm** [comment]
@KeenWarrior Done.

**Pull request closed without merging**
