### PR TITLE
Edit Profile UI added

### LINKED ISSUE #282: Design for Edit Profile in Profile Page
## Is your feature request related to a problem? Please describe.

Profile edit popup contain a form so that we can change the name , logo and email .

## Describe the solution you'd like
edit

### PR DESCRIPTION
**Pull request by poojadas07**
**Issue Number**

fixes #282 

**Describe the changes you've made**

Added the UI for edit profile so that we can change the profile photo, name and email.

**Checklist**

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.

profileeditPNG

### CODE REVIEW

**Comment by poojadas07** [comment]
@Abhishek-kumar09 Please check and let me know !!

**Review by Abhishek-kumar09 — COMMENTED** [review]
Give more padding between the components.

**Comment by poojadas07** [comment]
editprofile

Is that okay?

**Review by Abhishek-kumar09 — CHANGES_REQUESTED** [review]
Lessen the padding between two textFields.
Also, give option to change phone linkedIn, githubprofile etc.

**Comment by poojadas07** [comment]
> Lessen the padding between two textFields.
> Also, give option to change phone linkedIn, githubprofile etc.

Now how's it?

Cfg

**Comment by Abhishek-kumar09** [comment]
Facebook not required, only put twitter

**Comment by poojadas07** [comment]
> Facebook not required, only put twitter

okay....Anything else should I add?

**Comment by Abhishek-kumar09** [comment]
your code is not updated on github

**Comment by poojadas07** [comment]
> your code is not updated on github

Done

**Pull request merged**
