### PR TITLE
Added Links in Profile Page footer

### LINKED ISSUE #186: Adding Links to FAQ, About Us, Terms and Condition, and privacy policy
Add the Link to FAQ, About Us, Term of Use, and Privacy Policy so that they can redirect the user to the corresponding Page.

image

### PR DESCRIPTION
**Pull request by dhwaj1902**
**Issue Number**

fixes #186

### CODE REVIEW

**Review by Abhijay007 — COMMENTED** [review]
@dhwaj1902 remove text-decoration from the links and try to maintain the same CSS for text as it was before.

text-dec

**Comment by dhwaj1902** [comment]
image
Done

**Comment by dhwaj1902** [comment]
By mistake I have added pull request to this issue, actually the last  pull request is for issue#188
image

**Comment by Abhijay007** [comment]
> By mistake I have added pull request to this issue, actually the last pull request is for [Issue#188](https://github.com/codeforcauseorg/edu-client/issues/188#issue-848710582)
> image

@dhwaj1902 don't worry just add the edit issue number in the description to link that issue.

**Comment by Abhishek-kumar09** [comment]
Github, rebase

**Comment by Abhishek-kumar09** [comment]
Revert changes in package-lock.json

Just copy paste from the main repo

**Comment by dhwaj1902** [comment]
Sorry @Abhishek-kumar09 I don't understand, but why have you written these?

**Comment by Abhishek-kumar09** [comment]
I am saying that there are changes in `package-lock.json` but no new packages are installed. So we can revert those changes.

Please copy `package-lock.json` from main repo and paste it to your own repo and commit those.

**Comment by dhwaj1902** [comment]
@Abhishek-kumar09  done

**Pull request merged**
