### PR TITLE
Added "Hackathons And Events" page

### LINKED ISSUE #189: Adding a notification calendar/Progress bar for the user.
The user can get notifications of upcoming national level exams, competitions/Hackathons etc. Links to the competitions will be provided on a single click and the related courses can also be shown there.

### PR DESCRIPTION
**Pull request by Abhijay007**
fixes #189

**Describe the changes you've made**

Added hackathons and Events page where user can see ongoing and upcoming hackathons and events 

**Describe if there is any unusual behavior (Any Warning) of your code(Write `NA` if there isn't)**

`NA`

**Additional context (OPTIONAL)**

screenshot 1    |  screenshot 2       |  screenshot 3      |   
:-------------------------:|:-------------------------:|:-------------------------:|
hack1|hack2|hack3|

**Checklist**

- [x] My code follows the code style of this project.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.

**Provide a Deployed link of route/page that needs to review**

Preview: https://deploy-preview-323--edu-client.netlify.app/hackathonsAndEvents

### CODE REVIEW

**Comment by Abhijay007** [comment]
Yes! I take design inspiration from hacker Earth's official site. It is one
of the best site to know about hackathon and events because of its user
friendly experience. That's why I implement it in this site also !!

**Comment by Abhijay007** [comment]
@vasudevsinghal @Abhishek-kumar09, please review this PR and please let me know if this change is valid as per the use case of the application.

**Comment by sakshi-choudhary** [comment]
@Abhijay007  I think we already have a contests page, no need of lots of pages, but you can adjust this for know more in the contests page?

**Comment by Abhijay007** [comment]
> @Abhijay007 I think we already have a contests page, no need of lots of pages, but you can adjust this for know more in the contests page?

I think the contest page is for a different purpose. you can read details about the issue mentioned above, @Abhishek-kumar09 mentioned details in that issue.

**Review by Abhishek-kumar09 — APPROVED** [review]
Looks super Cool!

**Pull request merged**
