### PR TITLE
Course details

### PR DESCRIPTION
**Pull request by rajatgupta24**
**Issue Number**

fixes #

**Describe the changes you've made**
I've made changes to the course detail section 

**Describe if there is any unusual behavior (Any Warning) of your code(Write `NA` if there isn't)**
NA

**Additional context (OPTIONAL)**
NA

**Test plan (OPTIONAL)**
NA

A good test plan should give instructions that someone else can easily follow.

**Checklist**

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.

**Provide a Deployed link of route/page that needs to review**
Preview: Deploy preview link here with the appropriate route

<!-- Please add deployed link to here text >

### CODE REVIEW

**Comment by rajatgupta24** [comment]
Hey @Abhishek-kumar09, I create the course-detail section as per the new UI.

**Review by Abhishek-kumar09 — COMMENTED** [review]
image
Give it padding accordingly as drawn in the figma.
There is some responsive responsive issues in mobiles. Please check the design and try to correct it.

**Review by Abhijay007 — COMMENTED** [review]
@rajatgupta24  resolve merge conflicts

**Comment by Abhijay007** [comment]
@rajatgupta24 I think these changes gonna cover in this PR #357

**Pull request closed without merging**
