### PR TITLE
Added footer Section 

### PR DESCRIPTION
**Pull request by adarsh-technocrat**
**Describe the changes you've made**

**Describe if there is any unusual behavior (Any Warning) of your code(Write `NA` if there isn't)**

Added Responsive footer 

**Additional context (OPTIONAL)**

**Test plan (OPTIONAL)**

A good test plan should give instructions that someone else can easily follow.

**Checklist**

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.

**Provide a Deployed link of route/page that needs to review**
Preview: Deploy preview link here with the appropriate route

<!-- Please add deployed link to here text >

### CODE REVIEW

**Comment by adarsh-technocrat** [comment]
@Abhishek-kumar09  ping!!

**Review by Abhijay007 — COMMENTED** [review]
@adarsh-technocrat I think you mistakenly left a space in the naming convention of the social icons folder 
here :public/assets/icon/social icons/github.svg

 you can also skip this change if it is not necessary.

And one more thing when I checked the footer code for "iPad" in the tab view then there is horizontal space exists in the page, I am not sure about it as I am using the chrome inspect element for checking responsiveness. can you please cross-confirm it once?

ipad horizontal bar

although it is fine for all other screen sizes and it is also fine when I use the responsiveness tool instead of specifying "iPad".

**Comment by Abhijay007** [comment]
sorry for the late review 😅, I saw you just pushed one commit, my bad.

**Comment by adarsh-technocrat** [comment]
> although it is fine for all other screen sizes and it is also fine when I use the responsiveness tool instead of specifying "iPad".

Hey @Abhijay007 I have made changes according to the ideal sizes of the mobile, tab, and desktop for `iPad I need to be more specific but yaa! there is a slight horizontal space I'll resolve that !!

Thanks :)

**Review by Abhishek-kumar09 — APPROVED** [review]

**Pull request merged**
