### PR TITLE
Create Statistics Page

### PR DESCRIPTION
**Pull request by sakshi-choudhary**
**ISSUE #224**

**Describe the changes you've made**
Create Contests Statistics page.

**Describe if there is any unusual behavior (Any Warning) of your code(Write `NA` if there isn't)**
NA

**Checklist**

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.

**PREVIEW**

### CODE REVIEW

**Comment by sakshi-choudhary** [comment]
Please review @Abhishek-kumar09

**Comment by Abhishek-kumar09** [comment]
Resolve merge conflicts.

**Comment by sakshi-choudhary** [comment]
> Resolve merge conflicts.

Done. Please review @Abhishek-kumar09

**Review by Abhishek-kumar09 — COMMENTED** [review]
The scroll to top button is not working, remove it.

The charts are not aligned vertically.
Some letters from the are cutted down, very minor.

**Comment by sakshi-choudhary** [comment]
> The scroll to top button is not working, remove it.
> 
> The charts are not aligned vertically.
> Some letters from the are cutted down, very minor.

Done. Please review @Abhishek-kumar09 
Also, updated with a new feature.

Preview

**Comment by Abhishek-kumar09** [comment]
Looks good.

**Pull request merged**
