### PR TITLE
Mentor Rating and Review Page

### PR DESCRIPTION
**Pull request by sakshi-choudhary**
**ISSUE #206**

**Describe the changes you've made**
Create Mentor Rating Page.

**Describe if there is any unusual behavior (Any Warning) of your code(Write `NA` if there isn't)**
NA

**Additional context (OPTIONAL)**
Route-  /ratementor

**Checklist**

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.

**Preview of work done**

### CODE REVIEW

**Comment by sakshi-choudhary** [comment]
@Abhishek-kumar09 Could you please review and let me know for any changes required or anything more to add?

**Review by Abhijay007 — COMMENTED** [review]
@sakshi-choudhary it LGTM but I want to suggest a minor change that can you please add a link named 'feedback' in the profile section footer: 

for ref here:
profile-footer

it seems a nice thing that you made a mentor feedback page but can we also implement a general app feedback section? As I don't know that the feedback text field you implement in CFC feeds is for a mentor or for the app.

what are your thoughts on this can you implement a separate section for app review or feedback?

**Comment by sakshi-choudhary** [comment]
> @sakshi-choudhary it LGTM but I want to suggest a minor change that can you please add a link named 'feedback' in the profile footer section, it will help user to redirect to the page as you already implemented it in `routes.js` you just need to edit the footer text and need to add a redirect link to the text:
> 
> for ref here:
> profile-footer
> 
> for implementing this you just need to add general code like this
> 
> ```
>  {
>     id: 5,
>     link: "/ratementor",
>     title: "FEEDBACK",
>   },
> ```
> 
> you can find code for this here `src\pages\ProfilePage\ProfileComponent\FooterComponent.js` just follow this folder hierarchy.
> 
> it is good that you made a mentor feedback page but can we also implement a general app feedback section? As I don't know that the feedback text field you implement in CFC feeds is for the mentors only or for the App.
> 
> what are your thoughts on this can you implement a separate section for App review or feedback?

Thanks, for the suggestions but I have made this page a/c to given in the Figma design. I suppose this page is only for the feedback of the particular course mentor like there will be an option in a course to rate its mentor and give feedback to mentor's teaching.

**Comment by Abhijay007** [comment]
> Thanks, for the suggestions but I have made this page a/c to given in the Figma design. I suppose this page is only for the feedback of the particular course mentor like there will be an option in a course to rate its mentor and give feedback to the mentor's teaching.

oh ok, thanks for letting me know about it !!

**Review by Abhishek-kumar09 — APPROVED** [review]

**Pull request merged**
