### PR TITLE
Scroll to top on changing page.

### LINKED ISSUE #137: ScrollToTop on visiting every new tab in the bottom tab
## Describe the bug
When the page is scrolled down and swept left or right to another page , the new page is at the same scroll position at the previous page.

## To Reproduce

1.Make a complete reusable ScrollToTop component.
2.Add the ScrollToTop component at every tab (i.e Home , Courses, profile, etc. )

## Expected behavior
On swiping to the next the page will open from the top as scroll to top will be implemented for every Bottom Tab.

- OS: Windows
- Browser: Edge

### PR DESCRIPTION
**Pull request by ADRE9**
**Issue Number**
fixes #137 

**Describe the changes you've made**
On swiping to the next the page will open from the top as scroll to top will be implemented for every Bottom Tab.

**Additional context**
https://user-images.githubusercontent.com/49809895/112495154-a3add500-8da9-11eb-9145-d981a56d1d91.mp4

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Review by Abhishek-kumar09 — CHANGES_REQUESTED** [review]
We are not adding any package, so no change in lock file is expected

**Comment by ADRE9** [comment]
I'll check it tomorrow and make another PR.

**Comment by Abhishek-kumar09** [comment]
its good now i think, just add a linebreak at the end and two files will become identical

**Comment by ADRE9** [comment]
I'll re do it after my exams tomorrow.😕

**Pull request closed without merging**
