### PR TITLE
dotenv file added

### LINKED ISSUE #79: Create a .env file to store config keys
Create a .env file to store config keys of firebase auth.

### PR DESCRIPTION
**Pull request by Anurag5086**
**Issue Number**

fixes #79 

**Describe the changes you've made**
I have added a new env.example file. The firebase api key and auth domain is being taken from the environment variables. The config.js file as well had some constants which are also imported to the dotenv file.

**Describe if there is any unusual behavior (Any Warning) of your code(Write `NA` if there isn't)**

NA

**Checklist**

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Review by Abhishek-kumar09 — CHANGES_REQUESTED** [review]
Also add information in readme to how to setup the environment variable.

**Comment by Anurag5086** [comment]
> Also add information in readme to how to setup the environment variable.

I have made changes in README.md as well. Please check,

**Review by Anurag5086 — COMMENTED** [review]
Done

**Comment by Abhishek-kumar09** [comment]
Thanks @Anurag5086 for the PR

**Pull request merged**
