### PR TITLE
bottom nav and home corousel - design update

### PR DESCRIPTION
**Pull request by symaticvisuals**
npm run lint:fix is executed in this pull request

### CODE REVIEW

**Comment by symaticvisuals** [comment]
@Abhishek-kumar09 can you please help me with this?

**Review by adarsh-technocrat — COMMENTED** [review]
Hey, @symaticvisuals it's a prettier issue resolve that!
```shell

6:30:41 PM: src/layouts/MainLayout/BottomNav.js
6:30:41 PM:   Line 21:17:  Delete `·`  prettier/prettier
```

**Comment by symaticvisuals** [comment]
I had looked into it but am not getting it

**Comment by symaticvisuals** [comment]
@adarsh-technocrat please look into it now

**Review by Abhishek-kumar09 — COMMENTED** [review]
This looks monochromatic, redesigning on Figma will be much better choice if you like to change the designs of the pages.

**Comment by symaticvisuals** [comment]
Do we have figma designs as well?

**Pull request closed without merging**
