### PR TITLE
Take Notes Feature

### PR DESCRIPTION
**Pull request by sakshi-choudhary**
**ISSUE #152**

**Describe the changes you've made**

Added a floating action button to take notes while attending lectures.

**Describe if there is any unusual behavior (Any Warning) of your code(Write `NA` if there isn't)**
NA

**Checklist**

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.

**Provide a Deployed link of route/page that needs to review**
Preview: <a href="https://deploy-preview-267--festive-allen-a7f545.netlify.app/mycourses/:coursename">https://deploy-preview-267--festive-allen-a7f545.netlify.app/mycourses/:coursename</a>

### CODE REVIEW

**Comment by sakshi-choudhary** [comment]
@vasudev19126 @Abhishek-kumar09  Please review

**Comment by Abhishek-kumar09** [comment]
When I click on note add button the backtoTop button also get pops out.
image

**Comment by sakshi-choudhary** [comment]
> When I click on note add button the backtoTop button also get pops out.
> [image](https://user-images.githubusercontent.com/48255244/115152967-2405e400-a091-11eb-9ff5-534b08978f2b.png) 

I'm not sure why is this issue happening, for me the backtotop button only shows up when scroll down. I'm trying to resolve this issue. If you could give a hint on how to resolve this?

**Comment by Abhishek-kumar09** [comment]
Remove the back to Top button completely, it's not needed there I guess

**Comment by Abhishek-kumar09** [comment]
The User experience will not be good here since it is a very small text area, where people could barely write visible notes of 3 4 sentences.

How is the idea of using a Modal sheet: https://www.npmjs.com/package/react-modal-sheet

**Comment by sakshi-choudhary** [comment]
> The User experience will not be good here since it is a very small text area, where people could barely write visible notes of 3 4 sentences.
> 
> How is the idea of using a Modal sheet: https://www.npmjs.com/package/react-modal-sheet

yes, right. Sure I'll use this package and implement this.

**Comment by sakshi-choudhary** [comment]
Please review now @Abhishek-kumar09 . I have updated with react bottom modal

**Comment by Abhishek-kumar09** [comment]
Looks cool.

That green success snackbar was looking very nice in the previous UI. Can we use it here?

**Comment by sakshi-choudhary** [comment]
yes, sure. I'll add that again.

**Comment by sakshi-choudhary** [comment]
Done, @Abhishek-kumar09

**Comment by Abhishek-kumar09** [comment]
Thanks @sakshi-choudhary

**Pull request merged**
