### PR TITLE
Contributors section in README.md

### LINKED ISSUE #51: Add Credits Section in README.md for contributors
Have a credits section in our `README.md` file like [this](https://github.com/facebook/jest#credits) to recognise contributors in the project.

### PR DESCRIPTION
**Pull request by Harshal0902**
**Issue Number**

fixes #51 

**Describe the changes you've made**

Added a credits section in our `README.md` file like this to recognize contributors in the project.

**Describe if there is any unusual behavior (Any Warning) of your code(Write `NA` if there isn't)**

NA

**Additional context (OPTIONAL)**

**Test plan (OPTIONAL)**

A good test plan should give instructions that someone else can easily follow.

**Checklist**

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by kaiwalyakoparkar** [comment]
Why are these tests not passing

**Comment by Harshal0902** [comment]
Don't know, I only made changes in `README.md` file

**Comment by rajatgupta24** [comment]
Hi @Harshal0902,
I think the tests are failed because of the eslint errors, 
Just take the pull from main branch and they will be resolve.

**Comment by kaiwalyakoparkar** [comment]
@Harshal0902 try deleting this PR, then pull the recent changes made in the readme and then try adding these changes and then make a PR. Due to constant PR's in the readme this error maybe occuring

**Pull request closed without merging**
