### PR TITLE
Removed video-react and replaced it with React Player

### LINKED ISSUE #149: Video Player Consistency
## Describe the bug

There are currently two different video player packages. video-react and react-player. I think we only need one npm package which can be used for every purpose. React Player seems to be a better option as it is still being maintained.

## Additional context

If we agree on either package, we should remove the other package and use same player everywhere.

### PR DESCRIPTION
**Pull request by rizwan2000rm**
**Issue Number**

fixes #149 

**Describe the changes you've made**

Replaced video-react with react-player. Uninstalled video-react package from the project.

### CODE REVIEW

**Comment by Abhishek-kumar09** [comment]
Please Remove merge conflicts

**Comment by rizwan2000rm** [comment]
@Abhishek-kumar09 Done. I have integrated the changes according to new folder structure.

**Comment by Abhishek-kumar09** [comment]
Thanks @rizwan2000rm This is halted for some time, though it counts in your contribution.
I have halted it to check som more things which I could not check it now.

You can carry on to other PRs, I will get back to this after some time, and then we will do the required changes if any together.

**Comment by rizwan2000rm** [comment]
@Abhishek-kumar09 Sure. No problem.

**Comment by Abhijay007** [comment]
@rizwan2000rm resolve merge conflicts.

**Comment by rizwan2000rm** [comment]
@Abhijay007 This PR is halted for detailed review from @Abhishek-kumar09

**Comment by rizwan2000rm** [comment]
If this has to be tested now let me know I will fix the conflicts soon @Abhijay007 @Abhishek-kumar09

**Comment by Abhishek-kumar09** [comment]
Will update you on this.

**Comment by Abhijay007** [comment]
@rizwan2000rm  I think that this change will get covered In this PR (#367) you can close this PR if you want  :)

**Comment by Abhishek-kumar09** [comment]
No please keep it open. It's a good reference and thanks @rizwan2000rm for this PR

**Pull request closed without merging**
