### PR TITLE
Fix: contest page

### PR DESCRIPTION
**Pull request by rajatgupta24**
**Describe the changes you've made**
Hi @Abhishek-kumar09,
I made few changes to the contest page,
I changed the trophy icon with the material UI start icon (as it was slightly blurred),
And made the ongoing contest show by default
And change the text to typography 

image

**Describe if there is any unusual behavior (Any Warning) of your code(Write `NA` if there isn't)**

**Additional context (OPTIONAL)**

**Test plan (OPTIONAL)**

A good test plan should give instructions that someone else can easily follow.

**Checklist**

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.

**Provide a Deployed link of route/page that needs to review**
Preview: Deploy preview link here with the appropriate route
 

<!-- Please add deployed link to here text >

### CODE REVIEW

**Review by Abhijay007 — COMMENTED** [review]
@rajatgupta24 
LGTM 👍

**Comment by Abhishek-kumar09** [comment]
run `npm run lint:fix`

**Comment by rajatgupta24** [comment]
> run `npm run lint:fix`

Done

**Comment by Abhishek-kumar09** [comment]
The textField is left heavy
image

**Comment by Abhishek-kumar09** [comment]
Resolve conflicts.

and just like upcoming contests has different background color, choose success green variant for the completed contests.

**Comment by rajatgupta24** [comment]
Hey @Abhishek-kumar09, I made all the mentioned changes, kindly review the PR, & mention the changes if needed

**Comment by Abhishek-kumar09** [comment]
https://github.com/codeforcauseorg/edu-client/pull/268#issuecomment-822023819
This is not fixed.

Please make it fullWidth

**Comment by rajatgupta24** [comment]
Hey @Abhishek-kumar09, sorry for the delay but please review this.

**Comment by Abhishek-kumar09** [comment]
image
As you can see here, the texField is not full width, and for the cards the right margin is not the same as left margin. Right has very less margin.

**Comment by rajatgupta24** [comment]
Hey @Abhishek-kumar09, sorry for such a long delay, I'll be regular from now on.

**Pull request merged**
