### PR TITLE
Added Wishlist add and delete functions

### LINKED ISSUE #256: Add functionality to delete items from the wishlist section
## Is your feature request related to a problem? Please describe.

Add a user functionality to delete items/courses from the "Wishlist" section on click of that delete button.

## Additional context

wishlist-section

### PR DESCRIPTION
**Pull request by adarsh-technocrat**
**Issue Number**

fixes #256

**Describe the changes you've made**

**Describe if there is any unusual behavior (Any Warning) of your code(Write `NA` if there isn't)**

   Added Wishlist add and delete functions

**Additional context (OPTIONAL)**

**Test plan (OPTIONAL)**

A good test plan should give instructions that someone else can easily follow.

**Checklist**

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.

**Provide a Deployed link of route/page that needs to review**
Preview: Deploy preview link here with the appropriate route
 

<!-- Please add deployed link to here text >

### CODE REVIEW

**Comment by adarsh-technocrat** [comment]
Hey @Abhishek-kumar09  @vasudevsinghal  please review this PR !

Cc/ @Abhijay007

**Comment by adarsh-technocrat** [comment]
Hey, @Abhishek-kumar09 I have used a different approach for adding this functionality .

The things that are left to add are:- 
1. Notifying the user that the course has been added to the Wishlist.
2. Adding transition to the Wishlist card so that we can see that particular index is been deleted.
3. Adding Empty State UI to the Wishlist component basically which will be the initial state of the UI

**Comment by adarsh-technocrat** [comment]
@Abhishek-kumar09  I'll add different commits for above left things :)

**Comment by adarsh-technocrat** [comment]
Added empty wishlist component UI!

https://user-images.githubusercontent.com/47661086/116823061-e11f3280-ab9f-11eb-988d-99eadbae8626.mp4

**Review by Abhijay007 — COMMENTED** [review]
@adarsh-technocrat this code LGTM, I think this code is more efficient than mine PR. great work
I will try to modify that PR for some other issue. 👍

**Review by Abhishek-kumar09 — APPROVED** [review]
It's really good to see that you implemented Redux there.

**Pull request merged**
