### PR TITLE
Fix- Overexposed shadow blur radius of cards

### LINKED ISSUE #225: Fix- Overexposed shadow blur radius of cards
**Description**
The over-exposed shadow blur radius can be removed to make cards look cleaner and this needs to fix with all cards.

shadow

Cc/ @Abhishek-kumar09

### PR DESCRIPTION
**Pull request by naveen8801**
**Issue Number**

fixes #225 - Fix- Overexposed shadow blur radius of cards

**Describe the changes you've made**

i have added css style **boxShadow: "0px 0px 5px rgba(0,0,0,0.2)"** in wishlistCard component, courseCard component  and in HomeView page.

**After Changes**

border_shadow

- [x] My code follows the code style of this project.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by adarsh-technocrat** [comment]
Hey @naveen8801  you have not made changes to all the cards which have this issue, you can go for making changes to the rest of the cards too :)

**Comment by naveen8801** [comment]
> Hey @naveen8801 you have not made changes to all the cards which have this issue, you can go for making changes to the rest of the cards too :)

sure @adarsh-technocrat 👍

**Comment by naveen8801** [comment]
Hi @Abhishek-kumar09  @adarsh-technocrat , i found **className={classes.li}** in NonHero.js file in props passed to ListItem component , i think there is no use of this line because no such class exist , it may confuse some new comers so should i remove it ?   :) 

Screenshot (51)_LI

**Comment by adarsh-technocrat** [comment]
@naveen8801  you can remove that!

**Comment by adarsh-technocrat** [comment]
Hey, @naveen8801  can you please resolve this merge conflict?

**Comment by naveen8801** [comment]
> Hey, @naveen8801 can you please resolve the merge conflict?

Hii @adarsh-technocrat  , i have resolved the conflict , please review  :))

**Comment by Abhijay007** [comment]
@naveen8801 you can close this PR now as this issue is resolved from this PR (#327)

**Pull request closed without merging**
