### PR TITLE
Take notes feature added

### PR DESCRIPTION
**Pull request by ayush19030**
**Issue Number**

fixes #

**Describe the changes you've made**

**Describe if there is any unusual behavior (Any Warning) of your code(Write `NA` if there isn't)**

**Additional context (OPTIONAL)**

**Test plan (OPTIONAL)**

A good test plan should give instructions that someone else can easily follow.

**Checklist**

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by ayush19030** [comment]
@Abhishek-kumar09  Sir can you please review this and tell me of any concerns.

**Comment by Abhishek-kumar09** [comment]
The thing is good but not looking good.
image

Either add FloatingActionButton and add onClick event to it to open it to the screen.

**Comment by ayush19030** [comment]
Ok i will do it

**Comment by Abhijay007** [comment]
@ayush19030 you can close this PR as this issue os already resolved from @sakshi-choudhary 's PR (#267).

**Pull request closed without merging**
