### PR TITLE
Login page added

### PR DESCRIPTION
**Pull request by atharmohammad**
Issue #21 

**Describe the changes you've made**
Added Login  Page on Route /login and only when any account is logged in currently via google can access other routes and after user is logged in he can not access login page , currently just a testing loggedin variable is stored when logged in using google in localStorage , to test you can login using google and to logout just clear cache of your browser

you can see login page at route /login

**Describe if there is any unusual behavior (Any Warning) of your code(Write `NA` if there isn't)**
After logging in via google , I tried to redirect it to home using history.push('/home') after dispatch but redirect is not occuring
I tried it  by async await but nothing happens , So currently if you want to go to '/home' you have to type mannualy after logging in, I am looking into this Tell me if there is a way

**Checklist**

- [X] My code follows the code style of this project.
- [X] The title of my pull request is a short description of the requested changes.
log

### CODE REVIEW

**Review by Siddhant-K-code — CHANGES_REQUESTED** [review]
Did Your Try to run it offline, because it is giving a Compilation Error?

Also, Please remove or comment on unused variables.

image

**Comment by Siddhant-K-code** [comment]
Also, what you've changed so that `yarn.lock` and `package-lock.json` also get changed?

**Comment by atharmohammad** [comment]
@Siddhant-K-code  Yes, I ran it offline it was working fine, I asked in discord server and someone was saying that yarn.lock and oackage-lock.json will get updated with his PR after that this error will get sorted out,Tell me if there I should wait for his PR to get merged or there is a way....
I will be removing all unsused variables in next commit

**Comment by Siddhant-K-code** [comment]
why you closed this and created another PR? you can delete that files from here too!

**Comment by atharmohammad** [comment]
actually @Siddhant-K-code  I crated a new fork because my forked repo was polluted with so much and i did'nt know why checks error was occuring so I thought to start fresh and this time when i did'nt push yarn and package-lock.json checks passed,I think it was becasuse my react-scripts are of different version ,tell me what you think was the cause

**Pull request closed without merging**
