### PR TITLE
update scroll to top

### LINKED ISSUE #197: Scroll To Top not Working Properly
Currently, Scroll To Top Button is not working properly, we need to pull it down once to get to the top.

### PR DESCRIPTION
**Pull request by dhwaj1902**
**Issue Number**

fixes #197

### CODE REVIEW

**Comment by Abhishek-kumar09** [comment]
Github, rebase

**Comment by Abhishek-kumar09** [comment]
Github, rebase

**Comment by Abhishek-kumar09** [comment]
Thanks for the PR @dhwaj1902.
Just a minor change. 
Copy paste the package-lock.json file from the main repo to your own repo.

**Comment by Abhishek-kumar09** [comment]
Your package-lock.json file is not complete, it it not ending properly.

Also when you will be creating a new PR, try to rebase it tto your latest main branch.

**Comment by dhwaj1902** [comment]
@Abhishek-kumar09 ok I will keep that in mind.
Thanks.

**Pull request merged**
