### PR TITLE
Spelling mistake in read me file.

### PR DESCRIPTION
**Pull request by pruthvirajjadhav1**
**Issue Number**

fixes #86

**Describe the changes you've made**
There was a spelling mistake in read me file just fixed it. 

Please guide me if i am wrong its my first commit to this project .
Any suggetions for me. 

**Describe if there is any unusual behavior (Any Warning) of your code(Write `NA` if there isn't)**
NA

**Additional context (OPTIONAL)**

**Test plan (OPTIONAL)**

A good test plan should give instructions that someone else can easily follow.

**Checklist**

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by pruthvirajjadhav1** [comment]
Please give suggetions as its my first commit.

**Comment by kaiwalyakoparkar** [comment]
Good to know that @pruthvirajjadhav1 . Welcome to the community.Actually you have to make this change after #94 gets merged

**Comment by pruthvirajjadhav1** [comment]
> Good to know that @pruthvirajjadhav1 . Welcome to the community.Actually you have to make this change after #94 gets merged

I had made changes and commited is there anything else we have to do ?please guide me

**Comment by kaiwalyakoparkar** [comment]
> > Good to know that @pruthvirajjadhav1 . Welcome to the community.Actually you have to make this change after #94 gets merged
> 
> I had made changes and commited is there anything else we have to do ?please guide me

Actully PR #94 is fixing your issue. Soon project mentors are going to add more issues. you can always work on them

**Pull request closed without merging**
