### PR TITLE
Course Announcement Screen

### PR DESCRIPTION
**Pull request by sakshi-choudhary**
**ISSUE #257**

**Describe the changes you've made**
Developed Course Announcement Screen and comments page

**Describe if there is any unusual behavior (Any Warning) of your code(Write `NA` if there isn't)**

**Additional context (OPTIONAL)**
Linked the announcement page created under more options in my courses

**Checklist**

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.

**Provide a Deployed link of route/page that needs to review**
Preview: [https://deploy-preview-284--festive-allen-a7f545.netlify.app/mycourses/:coursename/announcement](https://deploy-preview-284--festive-allen-a7f545.netlify.app/mycourses/:coursename/announcement)

Screenshot 2021-04-24 at 00 50 20
Screenshot 2021-04-24 at 00 50 39

### CODE REVIEW

**Comment by sakshi-choudhary** [comment]
@Abhishek-kumar09 Please review

**Comment by Abhishek-kumar09** [comment]
It doesn't look like a course announcement page, but more like discussion forum.

**Comment by sakshi-choudhary** [comment]
> It doesn't look like a course announcement page, but more like discussion forum.

Okay so I actually took inspiration from the google classroom. Here, in this page only the course mentor can post something, like make an announcement, share some materials, and students can comment.
Students can't post anything. 
SO, this was the idea. If it doesn't make sense please let me know I will update this into the discussion forum page as anyways the discussion forum's UI is not good which is there right now. @Abhishek-kumar09

**Comment by sakshi-choudhary** [comment]
I will use this card component in the discussion forum and update this page with like a announcement notification thing.

**Comment by Abhishek-kumar09** [comment]
You can try creating design on Figma first, that will save a lot of effort of writing code again and again.
We can use the courseCards and show that they are upcoming, or having some announcements within it.

If the student are enrolled to a course, then there announcement may land into their `profile/announcements`.

**Pull request closed without merging**
