### PR TITLE
Shadow added to bottom navbar

### LINKED ISSUE #90: Add shadow to navbar
I think we should add some shadow to the top of the bottom-navbar.
image

### PR DESCRIPTION
**Pull request by poojadas07**
**Issue Number**

fixes #90 

**Describe the changes you've made**

I have added the shadow to the bottom navbar . Now it looks quite good .  

**Checklist**

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Review by rajatgupta24 — APPROVED** [review]
LGTM

**Comment by poojadas07** [comment]
> LGTM

**Comment by Abhishek-kumar09** [comment]
Thanks @poojadas07

**Comment by poojadas07** [comment]
> Thanks @poojadas07

Welcome @Abhishek-kumar09 . I am excitedly looking for new issues.

**Pull request merged**
