### PR TITLE
 Refactor and improve contest page UI

### LINKED ISSUE #259: Redesign UI  of the contest page
## Is your feature request related to a problem? Please describe.

**Proposed UI of the contest page** 

<p align ="middle">

</p>

As the previous Design of Contest page  was similar to the Assignment Section  I think this Proposed change can go well with the  contest page 

## Additional context

Add any other context about the feature request here.
 Cc/ @Abhishek-kumar09 , @KeenWarrior  , @kunal-kushwaha

### PR DESCRIPTION
**Pull request by adarsh-technocrat**
**Issue Number**

fixes #259

https://user-images.githubusercontent.com/47661086/114878151-92db0700-9e1d-11eb-80ef-f880b0e05a7d.mp4

**Describe the changes you've made**

**Describe if there is any unusual behavior (Any Warning) of your code(Write `NA` if there isn't)**

**Additional context (OPTIONAL)**

**Test plan (OPTIONAL)**

A good test plan should give instructions that someone else can easily follow.

**Checklist**

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.

**Provide a Deployed link of route/page that needs to review**
Preview: [Deployed preview link ](https://deploy-preview-263--festive-allen-a7f545.netlify.app/contests)
 

<!-- Please add deployed link to here text >

### CODE REVIEW

**Comment by adarsh-technocrat** [comment]
Hey, @Abhishek-kumar09  the UI is incomplete just wanted if could review this patch of code :)

**Comment by adarsh-technocrat** [comment]
Added Leaderboard elements 

https://user-images.githubusercontent.com/47661086/114896164-b6a64900-9e2d-11eb-95a7-fab53f1b7ce6.mp4

**Comment by adarsh-technocrat** [comment]
Added Stats elements 

https://user-images.githubusercontent.com/47661086/114977998-3cfe7180-9ea6-11eb-9fff-df1f3274317b.mp4

**Comment by adarsh-technocrat** [comment]
@Abhishek-kumar09  @vasudev19126 ping!

**Comment by adarsh-technocrat** [comment]
Hey @Abhishek-kumar09, @vasudev19126 I don't know if this change really required for the use case of the application if not, no worries I'll close this PR then and start working on another issue😃.

**Comment by Abhishek-kumar09** [comment]
It's looking good!, But instead of having this code on contest page, make another route and put that page into.

We can further take use of that design and make more changes on top of it to make something new or chnage existing ones.

The leaderboard and stats dashbaord can be used somewhere I think in the current contest page or dashboard page.

Please don't delete the currrent contest page fully.

**Comment by adarsh-technocrat** [comment]
> It's looking good! But instead of having this code on the contest page, make another route and put that page into.
> 
> We can further make use of that design and make more changes on top of it to make something new or change existing ones.
> 
> The leaderboard and stats dashboard can be used somewhere I think in the current contest page or dashboard page.
> 
> Please don't delete the current contest page fully.

Thanks, @Abhishek-kumar09 I'll make changes accordingly and keep the current contests page as it is and make a different route for this change :)

**Comment by adarsh-technocrat** [comment]
I'll revert you @Abhishek-kumar09 with the updated UI where we can fit stats and leaderboard components :)

**Pull request closed without merging**
