### PR TITLE
Schedule view

### LINKED ISSUE #4: Create schedule view for course page
Part 2 of #2 

image

Please see the parent issue for full design and more information.

### PR DESCRIPTION
**Pull request by faisaljamil25**
### Issue Number

fixes #4 

### Describe the changes you've made

Created course schedule component for the course details page.

### Describe if there is any unusual behavior (Any Warning) of your code(Write `NA` if there isn't)

NA

### Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by faisaljamil25** [comment]
Screenshots of the course schedule view. Please review and let me know what you think!

Screenshot 2021-03-11 022720

Screenshot 2021-03-11 022754

Screenshot (79)

**Review by Siddhant-K-code — CHANGES_REQUESTED** [review]
Remove Line 7 which you have commented in File:`src/components/courseDetals/scheduleDetails.js`

and make sure all files are formatted with Prettier

**Comment by faisaljamil25** [comment]
I have removed the commented lines and all the files are formatted with Prettier.

**Review by Siddhant-K-code — APPROVED** [review]
LGTM!

**Comment by Siddhant-K-code** [comment]
@KeenWarrior I think, we are good to go for this!

**Comment by Abhishek-kumar09** [comment]
Rebase your code to latest master, the themes are not applied to your changes as of now.

**Comment by faisaljamil25** [comment]
@Abhishek-kumar09 code is now up to date with the master branch.

**Review by Siddhant-K-code — APPROVED** [review]
All Good Now!

**Review by KeenWarrior — APPROVED** [review]

**Pull request merged**
