### PR TITLE
add UI fixes and create a component based structure

### PR DESCRIPTION
**Pull request by Devesh21700Kumar**
1).Changed this (also now one can change avatar based on name's first letter)

image

2). Instead of copying and pasting the same thing, i made a discussion component and mapped it for better modularity

### CODE REVIEW

**Comment by Devesh21700Kumar** [comment]
@Abhishek-kumar09 modularity based and UI based changes

**Comment by sakshi-choudhary** [comment]
@Devesh21700Kumar I think we should not show all the responses of a particular doubt on the same page as one doubt can have 100s of comments, so we can here follow the way Instagram does it. i.e we can write below the doubt 123 responses and on clicking on that the responses should open in a different page.

**Review by Abhijay007 — COMMENTED** [review]
@Devesh21700Kumar I think you need to pull upstream changes for the `main` branch in order to resolve these conflicts as the peer page is updated with one of the recent PR.

**Comment by Abhijay007** [comment]
@Devesh21700Kumar you can close this PR for now as `Discussion from` is refactored from this PR(#290), and your PR is based on the previous design so we may don't need this.
btw thanks for PR :)

**Pull request closed without merging**
