### PR TITLE
Add: Top bar Component

### LINKED ISSUE #276: Repeated Code
## Is your feature request related to a problem? Please describe.

Hey @Abhishek-kumar09, I noticed that we are writing the **top navigation** in each section page which is not preferable & using **Back Arrow** on pages like **wishlist**, **myCourses**, or **profile** doesn't make sense.

## Describe the solution you'd like

I think it's better to create a **component** for **top navigation** for the page where we're not having **bottomNav**

## Additional context

Add any other context about the feature request here.

### PR DESCRIPTION
**Pull request by rajatgupta24**
**Issue Number**
fixes #276 

**Describe the changes you've made**
I've created a TopBar component to remove the repeated code for every page of the back button.
I've also created options for the shareBtn & more options as well.

**Describe if there is any unusual behavior (Any Warning) of your code(Write `NA` if there isn't)**
NA

**Additional context (OPTIONAL)**
NA

**Test plan (OPTIONAL)**

**Checklist**

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.

**Provide a Deployed link of route/page that needs to review**
Preview: Deploy preview link here with the appropriate route

<!-- Please add deployed link to here text >

### CODE REVIEW

**Comment by rajatgupta24** [comment]
Hey @Abhishek-kumar09, tell me if changes needs to be done.

**Review by Abhijay007 — COMMENTED** [review]
@rajatgupta24 thanks for PR but I think this change is not in the new UI on which @adarsh-technocrat is working. In that UI (as far as I know ) we are not using this topbar approach as we are now making App for both web and mobile devices.  

topbar should be responsive according to the current UI. In that case, we may not use this share app functionality in the topbar.

**Comment by rajatgupta24** [comment]
Hey @Abhijay007, @adarsh-technocrat I just replaced the repeated code of the back button on the top with the name of the component & the share button & menu option.

This same code was written in each section so I just made a component to the code less repeated.

@Abhijay007 the profile page uses the back button (topBar) & it has the share button.

**Comment by Abhijay007** [comment]
> @Abhijay007 the profile page uses the back button (topBar) & it has the share button.

@rajatgupta24  in the new UI we are using a different approach for the profile page (topbar) it may not have a back button and share button.

**Comment by rajatgupta24** [comment]
> new UI we are using a different approach for the profile page (topbar) it may not have a back button and share button.

@Abhijay007 Can you please share the UI

**Comment by Abhishek-kumar09** [comment]
Hey @rajatgupta24 here is the figma
https://www.figma.com/file/0IsoLxDMwlgPbPXSmpLhDo/Edu-client-Application-UI-Duplicate?node-id=366%3A344

**Comment by rajatgupta24** [comment]
> Hey @rajatgupta24 here is the figma
> https://www.figma.com/file/0IsoLxDMwlgPbPXSmpLhDo/Edu-client-Application-UI-Duplicate?node-id=366%3A344

Hey @Abhishek-kumar09, It says "you don't have permission".

**Comment by Abhishek-kumar09** [comment]
@rajatgupta24 https://www.figma.com/file/0IsoLxDMwlgPbPXSmpLhDo/Edu-client-Application-UI-(Duplicate)?node-id=0%3A1

Please check now if it working fine.

**Comment by rajatgupta24** [comment]
I'm closing this PR

**Pull request closed without merging**
