### PR TITLE
Bottom Navbar bug (hidden on scroll down)

### LINKED ISSUE #95: Bottom navbar get hidden when scrolled down.
## Describe the bug

Bottom nanvbar is hidden when scrolled down to the limit
This bug may have introduced here: https://github.com/codeforcauseorg/edu-client/pull/63

## To Reproduce

1. Open application in development mode.
2. scroll down to bottom and bottom navabar will be disappeared once.

## Environment (please complete the following information):

- OS: Ubuntu
- Browser: Google chrome

### PR DESCRIPTION
**Pull request by Abhijay007**
fixes #95 

**Describe the changes you've made**

Removed unwanted code for scroll action and fade effect for the bottom navbar.

**Describe if there is any unusual behavior (Any Warning) of your code(Write `NA` if there isn't)**

`NA`

**Additional context (OPTIONAL)**

Android view through chrome inspect:

android-view

web view:

web view

**Test plan (OPTIONAL)**

Tested On my local Machine and Browser.

OS: windows
Browser: chrome

**Checklist**

- [x] My code follows the code style of this project.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Review by rajatgupta24 — CHANGES_REQUESTED** [review]
@Abhijay007 please follow the coding style we use, this will help you to solve the failure of the commit.

**Comment by Abhijay007** [comment]
Ok

**Comment by Abhijay007** [comment]
> @Abhijay007 please follow the coding style we use, this will help you to solve the failure of the commit.

@rajatgupta24 I formatted code accordingly but the test still fails can you please tell me where I made the mistake

**Comment by Abhijay007** [comment]
@Abhishek-kumar09 sir can you please tell me where I made the mistake or why these checks were failed?

**Comment by Abhishek-kumar09** [comment]
Github, rebase

**Comment by Abhishek-kumar09** [comment]
Looks good.

**Pull request merged**
