### PR TITLE
Add: static pages

### LINKED ISSUE #48: Add: about us page
Hi @KeenWarrior @kunal-kushwaha ,
We should add:

- About us page
- Terms & condition
- Privacy policy

Can I work on them.

### PR DESCRIPTION
**Pull request by rajatgupta24**
**Issue Number**

fixes #48

**Describe the changes you've made**
Created  DocsLayout & document folders
Now we can convert md file to jsx.

**Describe if there is any unusual behavior (Any Warning) of your code(Write `NA` if there isn't)**
Due to eslint there are some error occured due to which some changes were made in unretated file.  

**Checklist**

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by kaiwalyakoparkar** [comment]
Could you please share screenshots of your output? It is very hard to make intuition based on your code

**Comment by rajatgupta24** [comment]
image
image
image

**Comment by rajatgupta24** [comment]
Hi @KeenWarrior, @Abhishek-kumar09  can you please review.

**Review by Amulya-coder — CHANGES_REQUESTED** [review]
@rajatgupta24 please resolve the conflicts.

**Pull request closed without merging**
