### PR TITLE
Added: Job opening page

### PR DESCRIPTION
**Pull request by adarsh-technocrat**
**Issue Number**

fixes  related issue  #135

**Describe the changes you've made**

 Added menu in Student dashboard app bar `morevert` icon button which will navigate to job openings section!

**Describe if there is any unusual behavior (Any Warning) of your code(Write `NA` if there isn't)**

**Additional context (OPTIONAL)**

**Test plan (OPTIONAL)**

A good test plan should give instructions that someone else can easily follow.

**Checklist**

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.

**Snapshot**
job page

Cc/ @Abhishek-kumar09

### CODE REVIEW

**Comment by rajatgupta24** [comment]
Hey @adarsh-technocrat, can you please add a screenshot of the changes.

**Comment by adarsh-technocrat** [comment]
> Hey @adarsh-technocrat, can you please add a screenshot of the changes.

Sure thing @rajatgupta24!

**Review by rajatgupta24 — APPROVED** [review]
LGTM :+1:

**Comment by adarsh-technocrat** [comment]
> Please resolve merge conflicts.

resolved @Abhishek-kumar09  :)

**Comment by Abhishek-kumar09** [comment]
Looks pretty

**Pull request merged**
