### PR TITLE
Added Continue learning section in Home Page 

### PR DESCRIPTION
**Pull request by adarsh-technocrat**
**Issue Number**

fixes #

**Describe the changes you've made**

**Describe if there is any unusual behavior (Any Warning) of your code(Write `NA` if there isn't)**

Added Continue learning section in Home Page  made responsive for web, tab , mobile 

**Additional context (OPTIONAL)**

**Test plan (OPTIONAL)**

A good test plan should give instructions that someone else can easily follow.

**Checklist**

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.

**Provide a Deployed link of route/page that needs to review**
Preview: Deployed preview link 

<!-- Please add deployed link to here text >

Cc: @Abhishek-kumar09

### CODE REVIEW

**Review by Abhijay007 — COMMENTED** [review]
@adarsh-technocrat I think if we apply a little bit of shadow in the background or add a border to the learning card then it looks better.

One thing more I want to mention that when we hover on cards then that effect causes a bit of blurriness to the cards I am not sure about it but I think it exists in the effect for desktop view.

**Comment by Abhijay007** [comment]
> @adarsh-technocrat I think if we apply a little bit of shadow in the background or add a border to the learning card then it looks better.
> 
> One thing more I want to mention that when we hover on cards then that effect causes a bit of blurriness to the cards I am not sure about it but I think it exists in the effect for desktop view.

you cover this in one of your future PRs as I know it is just a component for now.

**Comment by adarsh-technocrat** [comment]
> @adarsh-technocrat I think if we apply a little bit of shadow in the background or add a border to the learning card then it looks better.
>

Hey, @Abhijay007  added a bit of shadow to the card !!    :)

**Comment by adarsh-technocrat** [comment]
> One thing more I want to mention that when we hover on cards then that effect causes a bit of blurriness to the cards I am not sure about it but I think it exists in the effect for desktop view.

Actually @Abhijay007, the issue is with the `transform scale` and `browser` compatibility issue with it there are various approaches to solve that issue but that would not be the right approach so I have made few changes to the hover that look's fine and can go with it.

Revert me if you find any issue with the latest changes :)

**Comment by Abhishek-kumar09** [comment]
Closing this PR for now, since all the changes are there in https://github.com/codeforcauseorg/edu-client/pull/343 
Right @adarsh-technocrat ? 
We can handle that in that PR. Thanks for review @Abhijay007

**Comment by adarsh-technocrat** [comment]
@Abhishek-kumar09 I would  suggest mergee  this PR #345  !!

**Comment by adarsh-technocrat** [comment]
That was the last PR which I made which includes all the changes !!

**Pull request closed without merging**
