### PR TITLE
aligned back-to-top button to extreme bottom

### PR DESCRIPTION
**Pull request by Abhijay007**
**Describe the changes you've made**

Aligned back to top button to extreme bottom of the page in order to improve UI as it is currently in middle somewhere which will not justify its use.

**Describe if there is any unusual behavior (Any Warning) of your code(Write `NA` if there isn't)**

`NA`

**Additional context (OPTIONAL)**

***before***
before-backToTop

***after***
after-backToTop

**Checklist**

- [x] My code follows the code style of this project.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Review by rajatgupta24 — COMMENTED** [review]
Hi @Abhijay007, the changes you made are good but can you also remove the extra space btw the cards and the button.

**Comment by Abhijay007** [comment]
> Hi @Abhijay007, the changes you made are good but can you also remove the extra space btw the cards and the button.

Ok thanks, @rajatgupta24 for reviewing this PR, I will try to remove that space 👍

**Comment by Abhishek-kumar09** [comment]
> Hi @Abhijay007, the changes you made are good but can you also remove the extra space btw the cards and the button.

yes, that is main problem, page height is more than actual required height.

**Comment by Abhijay007** [comment]
> > Hi @Abhijay007, the changes you made are good but can you also remove the extra space btw the cards and the button.

> yes, that is main problem, page height is more than actual required height.

@rajatgupta24 @Abhishek-kumar09 can you please help me with this height issue, I tried to resolve it for the past 5 days but not able to find any optimized solution. i think that some of the container classes overwriting each other which leds to this height issue as you can see in the console snip below there are some of the containers that form a hierarchy. 

containers-console

these containers are overwriting the properties of each other.

I try to manipulate height using inline CSS and even use `! Important` property of CSS in order to ignore that overwriting thing but not able to find any thing fruitful, I don't know where I made the mistake can you please help me with this or suggest me something to solve this.

**Comment by Abhishek-kumar09** [comment]
> > > Hi @Abhijay007, the changes you made are good but can you also remove the extra space btw the cards and the button.
> 
> > yes, that is main problem, page height is more than actual required height.
> 
> @rajatgupta24 @Abhishek-kumar09 can you please help me with this height issue, I tried to resolve it for the past 5 days but not able to find any optimized solution. i think that some of the container classes overwriting each other which leds to this height issue as you can see in the console snip below there are some of the containers that form a hierarchy.
> 
> containers-console
> 
> these containers are overwriting the properties of each other.
> 
> I try to manipulate height using inline CSS and even use `! Important` property of CSS in order to ignore that overwriting thing but not able to find any thing fruitful, I don't know where I made the mistake can you please help me with this or suggest me something to solve this.

Okay No problem, we can check that out after some time. Till then you can try some other issues or write your proposal

**Comment by Abhijay007** [comment]
closing this PR, related to previous UI design : )

**Pull request closed without merging**
