### PR TITLE
Shadow portion removed from cards

### LINKED ISSUE #315: Recent Searches section in home page
## Is your feature request related to a problem? Please describe.

Recent searches section in homepage. 
 
## Describe the solution you'd like

I want to add one more section in home page which contains all the recent searches of the particular login user. Recent searches vary from user to user according to userId or userEmail.

### PR DESCRIPTION
**Pull request by poojadas07**
**Issue Number**

fixes #315 

**Describe the changes you've made**

Shadow portion removed from all the cards.

### CODE REVIEW

**Review by Abhishek-kumar09 — COMMENTED** [review]
The changes are fully removing the shadow, we want a bit of shadow.

See this, we will be implementing shadow like this so that MUI cards and papers could get elevation property.
https://github.com/codeforcauseorg/edu-client/tree/temp_shadow

Test it locally, and propose new changes if needed or make/modify PR according to https://github.com/codeforcauseorg/edu-client/tree/temp_shadow

**Comment by poojadas07** [comment]
> The changes are fully removing the shadow, we want a bit of shadow.
> 
> See this, we will be implementing shadow like this so that MUI cards and papers could get elevation property.
> https://github.com/codeforcauseorg/edu-client/tree/temp_shadow
> 
> Test it locally, and propose new changes if needed or make/modify PR according to https://github.com/codeforcauseorg/edu-client/tree/temp_shadow

sure...

**Comment by poojadas07** [comment]
dec

@Abhishek-kumar09 check !!

**Comment by poojadas07** [comment]
> dec
> 
> @Abhishek-kumar09 check !!

@Abhishek-kumar09 Please check and let me know is this okay or not?

**Pull request merged**
