### PR TITLE
Fix: continue learning cards

### LINKED ISSUE #140: Fix: continue learning cards
Hi guys,
It's hard to scroll through the continue learning section when we've a lot of courses going on.

I think the cards in continue learning section can be better is they are in horizontal scroll. 

It'll make it short and mobile friendly.
*I can make the changes in my PR #85 because it contains similar functionality.*

### PR DESCRIPTION
**Pull request by naveen8801**
**Issue Number**

fixes #140 

**Describe the changes you've made**

styling of  'root' section in 'coursecard1' component edited , stylings for 'List' element added in 'Non.Hero.js'

**Additional context (OPTIONAL)**

Screenshot (33)

**Test plan (OPTIONAL)**

A good test plan should give instructions that someone else can easily follow.

**Checklist**

- [x] My code follows the code style of this project.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by adarsh-technocrat** [comment]
Hello, @naveen8801  thanks for the PR I have some suggestions related to PR  when it comes to mobile application View and use case for adding a Horizontal Scroll View we don't see that `horizontal Scroll bar` right!  so if @Abhishek-kumar09  agrees with the point you can go for removing the  ` horizontal Scroll bar`  and you can remove other  ` horizontal Scroll bar`  as well :)

**Comment by adarsh-technocrat** [comment]
@naveen8801  Can you please go for resolving that deleted `package-lock.json `  file from your PR  as that should not be included in your PR :)

**Comment by naveen8801** [comment]
Hii @adarsh-technocrat , thanks for suggestion , i have implemented all the changes suggested by you  .

Screenshot (35)

But my test cases are falling , please help !

**Comment by adarsh-technocrat** [comment]
Actually, there are some prettier issues resolve that
```
src/pages/HomeView/NonHero.js
  Line 19:14:  Replace `·:·"none"` with `:·"none",`  prettier/prettier
  Line 42:1:   Delete `··`                           prettier/prettier

```

**Review by Abhishek-kumar09 — CHANGES_REQUESTED** [review]
Nice changes, please don't delete lock file.
Copy paste lock file from the main repo and add it to your commit

**Pull request merged**
