### PR TITLE
Added Popular course section In Home Page 

### PR DESCRIPTION
**Pull request by adarsh-technocrat**
**Describe the changes you've made**

**Describe if there is any unusual behavior (Any Warning) of your code(Write `NA` if there isn't)**

Added Popular course section In Home Page 

**Additional context (OPTIONAL)**

**Test plan (OPTIONAL)**

A good test plan should give instructions that someone else can easily follow.

**Checklist**

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.

**Provide a Deployed link of route/page that needs to review**
Preview: Deployed preview link

Cc: @Abhishek-kumar09

### CODE REVIEW

**Comment by Abhishek-kumar09** [comment]
Can we have some more bottom padding in the cards
image

**Comment by adarsh-technocrat** [comment]
> Can we have some more bottom padding in the cards
> image

@Abhishek-kumar09 I have made all minor changes in the upcoming PR which resolves all these issues :)

**Comment by adarsh-technocrat** [comment]
> **A reviewer left a comment:**
> 
> Had you added any content in Popular Courses?
> 
> Browser metadata
> [Open Deploy Preview](https://deploy-preview-343--edu-client.netlify.app/home) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=60b333aca8083200087bf690&commentID=60b3553937549549a0cc1a82&resolution=resolved)

Yes, will be shortly pushing the changes from the local branch :)

**Comment by adarsh-technocrat** [comment]
@Abhishek-kumar09 I'll destructure the props as I implement the mock data to the component!

**Pull request merged**
