### PR TITLE
Adds a Dynamic Data based profile Page with cards and recently played functionality

### PR DESCRIPTION
**Pull request by Devesh21700Kumar**
fixes # Adds a Dynamic Data based profile Page

**Describe the changes you've made**

A profile page made with Avatar and first five of the recently played videos by a person
Mobile view

image

Mobile View 

image

desktop view 

image

desktop view scrolled down

image

i've set slice(0,5) before mapping so in recently played only 1st 5 will appear.. its different from history

**Checklist**

- [x ] My code follows the code style of this project.

- [ x] All new and existing tests passed.
- [x ] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by Devesh21700Kumar** [comment]
@Abhishek-kumar09 please review the PR
@rizwan2000rm please review the PR

**Comment by kaiwalyakoparkar** [comment]
- Can you center the log-out button. As it is in fill-parent it looks somewhat absurd. If you could make it of the same size but center aligned then it would look great.
- Please change the gradient of red to a somewhat darker red
- Highlight the Logout text
- If the logout button is at the top then it will make the design more sustainable. Else if the user has registered for many courses. He will have to scroll a long way down.

**Comment by Devesh21700Kumar** [comment]
> * Can you center the log-out button. As it is in fill-parent it looks somewhat absurd. If you could make it of the same size but center aligned then it would look great.
> * Please change the gradient of red to a somewhat darker red
> * Highlight the Logout text
> * If the logout button is at the top then it will make the design more sustainable. Else if the user has registered for many courses. He will have to scroll a long way down.

sure .. Thanks

**Comment by Devesh21700Kumar** [comment]
> * Can you center the log-out button. As it is in fill-parent it looks somewhat absurd. If you could make it of the same size but center aligned then it would look great.
> * Please change the gradient of red to a somewhat darker red
> * Highlight the Logout text
> * If the logout button is at the top then it will make the design more sustainable. Else if the user has registered for many courses. He will have to scroll a long way down.

Mobile view

image

Desktop view

image

**Comment by Devesh21700Kumar** [comment]
@Abhishek-kumar09 @KeenWarrior pls see

**Comment by Abhishek-kumar09** [comment]
The profile page design is in progress, your work is appreciated and acknowledged!
Thanks for the PR

**Comment by Abhijay007** [comment]
@Devesh21700Kumar I think you can close this PR now as there is already a profile Page that exists in the `main` branch and as @adarsh-technocrat is working on a new UI design we may need to make a profile page according to that design.

**Pull request closed without merging**
